version: "1.0"
services:
  database:
    container_name: db-lab
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./backend/src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=defensa2001
      - POSTGRES_DB=fingerprints
    ports:
      - 5432:5432
  backend:
    container_name: backend-lab
    image: rust:latest
    environment:
      - SOCKET_IP=192.168.68.112
      - SOCKET_PORT=5000
    volumes:
      - "./backend:/app"
    working_dir: /app
    command: bash -c "curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash && cargo binstall -y cargo-watch && cargo watch -x run"
  frontend:
    container_name: frontend-lab
    image: node:18
    volumes:
      - "./frontend:/app"
    working_dir: /app
    command: bash -c "npm i -g vite && yarn install && vite"

  web:
    container_name: web
    image: nginx
    depends_on:
      - backend
      - frontend
      - database
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./pem:/pem
    ports:
      - "8001:443"
    environment:
      - NGINX_HOST=someweb.com
      - NGINX_PORT=80

volumes:
  db-data:
