[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.18", default-features = false, features = ["headers", "http1", "json", "tokio", "tower-log","query"] }
bcrypt = "0.14.0"
chrono = "0.4.26"
dotenvy = "0.15.7"
dotenvy_macro = "0.15.7"
jsonwebtoken = {version = "8.3.0", default-features = false }
regex = { version = "1.8.4", default-features = false, features = ["std", "unicode-perl"] }
sea-orm = { version = "0.11.3", features = [
  "sqlx-postgres",
  "runtime-tokio-rustls",
  "macros",
] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
sqlx = { version = "0.6.3", features = ["postgres"] }
tokio = { version = "1.28.2", features = ["rt-multi-thread", "macros", "tracing"] }
tower-http = { version = "0.4.0", features = ["cors"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"

[profile.release]
opt-level = 3
codegen-units = 1
panic = "abort"
strip = true
lto = true