#!/bin/bash

# Check if two arguments are passed
if [ "$#" -ne 2 ]; then
    echo "Usage: $0 --server|--socket <ip>"
    exit 1
fi

TARGET_IP=$2

ENV_FILE=".env"
if [ ! -f "$ENV_FILE" ]; then
    echo "Error: .env file not found!"
    exit 1
fi
OLD_IP_SERVER=$(grep "^VITE_BACKEND_IP=" "$ENV_FILE" | cut -d '=' -f 2)
OLD_IP_SOCKET=$(grep "^SOCKET_IP=" "$ENV_FILE" | cut -d '=' -f 2)

# Check if OLD_IP was found
if [ -z "$OLD_IP_SERVER" ]; then
    echo "Error: VITE_BACKEND_IP not found in $ENV_FILE"
    exit 1
fi

if [ -z "$OLD_IP_SOCKET" ]; then
    echo "Error: SOCKET_IP not found in $ENV_FILE"
    exit 1
fi

# Handle the first argument
case "$1" in
    --server)
        # Find the .js file in the directory
        JS_FILE=$(find frontend/assets/ -type f -name "*.js" | head -n 1)
        # Check if the .js file was found
        if [ -z "$JS_FILE" ]; then
            echo "Error: No .js file found"
            exit 1
        fi
        # Replace the old IP with the new IP in the found .js file
        sed -i "s/$OLD_IP_SERVER/$TARGET_IP/g" "$JS_FILE"
        sed -i "s/$OLD_IP_SERVER/$TARGET_IP/g" .env
        ;;
    --socket)
        sed -i "s/$OLD_IP_SOCKET/$TARGET_IP/g" .env
        ;;
    *)
        echo "Invalid option: $1. Use --server or --socket."
        exit 1
        ;;
esac
