version: "1.0"
services:
  database:
    container_name: database
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=defensa2001
      - POSTGRES_DB=fingerprints
    ports:
      - 5432:5432
  backend:
    container_name: backend
    image: ubuntu:latest
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/backend
    environment:
      - SOCKET_IP=192.168.68.112
      - SOCKET_PORT=5000
    depends_on:
      - database
    command: bash -c './backend'
  web:
    container_name: webserver
    image: nginx
    depends_on:
      - backend
      - database
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/frontend
    ports:
      - "8001:80"
    environment:
      - NGINX_HOST=someweb.com
      - NGINX_PORT=80
volumes:
  db-data:
