name: Rust

on:
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        cd backend
        cargo build --verbose
